name: Deploy static site to S3
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::128448363746:role/github-actions-greenewebdev.net
          aws-region: us-east-1
      - name: Sync to S3
        run: |
          aws s3 sync . s3://greenewebdev-net-site/ \
            --exclude ".git/*" --exclude ".github/*" --exclude ".DS_Store" \
            --delete --exact-timestamps
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2SHF2JXGVEXR5 \
            --paths "/*"
